# Generated by Django 5.1.3 on 2025-01-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_categories_products_categories_descrption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images/')),
                ('productName', models.CharField(max_length=50)),
                ('productPrice', models.FloatField()),
            ],
        ),
    ]
