# Generated by Django 5.1.3 on 2025-01-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='productPrice',
            field=models.IntegerField(null=True),
        ),
    ]
