# Generated by Django 5.1.3 on 2025-01-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_products_productprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Category',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
