# Generated by Django 5.1.3 on 2025-01-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='category',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
