# Generated by Django 5.1.3 on 2025-01-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_categories_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='category',
        ),
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
