# Generated by Django 5.1.3 on 2025-01-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_products_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='number',
        ),
        migrations.AddField(
            model_name='cart',
            name='number',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
