# Generated by Django 5.1.3 on 2025-02-03 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_cart_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
