# Generated by Django 5.1.3 on 2025-02-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Discount',
            field=models.IntegerField(null=True),
        ),
    ]
