# Generated by Django 5.1.3 on 2025-02-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_products_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Discount',
            field=models.IntegerField(default=0),
        ),
    ]
