# Generated by Django 5.1.3 on 2025-02-13 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_products_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='Category',
        ),
    ]
