# Generated by Django 5.1.3 on 2025-02-13 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.categories'),
        ),
    ]
